{
  'patch_text': '!file @5->6\n'
    '=c\n'
    '+a\n'
    '#x\n'
    '-b\n'
    '=c\n',
  'result': PatchFile(
    chunks=[
      EditOperation(
        path='file',
        line_hint=(
          5,
          6,
        ),
        lines=[
          ContextLine(
            content='c\n',
          ),
          AddedLine(
            content='a\n',
          ),
          RemovedLine(
            content='b\n',
          ),
          ContextLine(
            content='c\n',
          ),
        ],
      ),
    ],
  ),
}